=== seanthorne/TalentIQ-V3-API-Resources/schemas/title/title-success-response-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "errors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    }
                }
            }
        },
        "message": {
            "type": "string"
        },
        "status": {
            "type": "number"
        },
        "data": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "levels": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "related": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "functions": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "related": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "rank": {
                                            "type": "number"                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== seanthorne/TalentIQ-V3-API-Resources/schemas/title/title-success-response-example.json
{
    "data": {
        "functions": [
            {
                "name": "software engineer", 
                "related": [
                    {
                        "name": "software engineer", 
                        "rank": 1
                    }, 
                    {
                        "name": "mid level software engineer", 
                        "rank": 2
                    }, 
                    {
                        "name": "intermediate software engineer", 
                        "rank": 3
                    }, 
                    {
                        "name": "application software engineer", 
                        "rank": 4
                    }, 
                    {
                        "name": "intermediate software developer", 
                        "rank": 5
                    }, 
                    {
                        "name": "software developer", 
                        "rank": 6
                    }, 
                    {
                        "name": "software designer", 
                        "rank": 7
                    }, 
                    {
                        "name": "software engineer specialist", 
                        "rank": 8
                    }, 
                    {
                        "name": "software developer specialist", 
                        "rank": 9
                    }, 
                    {
                        "name": "part time software developer", 
                        "rank": 10
                    }, 
                    {
                        "name": "assoc software engineer", 
                        "rank": 11
                    }, 
                    {
                        "name": "software analyst", 
                        "rank": 12
                    }, 
                    {
                        "name": "programmer", 
                        "rank": 13
                    }, 
                    {
                        "name": "experienced software engineer", 
                        "rank": 14
                    }, 
                    {
                        "name": "software specialist", 
                        "rank": 15
                    }, 
                    {
                        "name": "expert software engineer", 
                        "rank": 16
                    }, 
                    {
                        "name": "server developer", 
                        "rank": 17
                    }, 
                    {
                        "name": "software developer analyst", 
                        "rank": 18
                    }, 
                    {
                        "name": "enterprise developer", 
                        "rank": 19
                    }, 
                    {
                        "name": "developer", 
                        "rank": 20
                    }, 
                    {
                        "name": "software developer engineer", 
                        "rank": 21
                    }, 
                    {
                        "name": "tech leader", 
                        "rank": 22
                    }, 
                    {
                        "name": "platform developer", 
                        "rank": 23
                    }, 
                    {
                        "name": "asst software engineer", 
                        "rank": 24
                    }, 
                    {
                        "name": "c programmer", 
                        "rank": 25
                    }, 
                    {
                        "name": "web services developer", 
                        "rank": 26
                    }, 
                    {
                        "name": "software engineer team leader", 
                        "rank": 27
                    }, 
                    {
                        "name": "software programmer", 
                        "rank": 28
                    }, 
                    {
                        "name": "graduate software engineer", 
                        "rank": 29
                    }, 
                    {
                        "name": "visual basic developer", 
                        "rank": 30
                    }, 
                    {
                        "name": "database software developer", 
                        "rank": 31
                    }, 
                    {
                        "name": "independent software developer", 
                        "rank": 32
                    }, 
                    {
                        "name": "vb developer", 
                        "rank": 33
                    }, 
                    {
                        "name": "expert developer", 
                        "rank": 34
                    }, 
                    {
                        "name": "contract software engineer", 
                        "rank": 35
                    }, 
                    {
                        "name": "software application engineer", 
                        "rank": 36
                    }, 
                    {
                        "name": "leading developer", 
                        "rank": 37
                    }, 
                    {
                        "name": "developer analyst", 
                        "rank": 38
                    }, 
                    {
                        "name": "leading software developer", 
                        "rank": 39
                    }, 
                    {
                        "name": "independent software engineer", 
                        "rank": 40
                    }, 
                    {
                        "name": "software developer team leader", 
                        "rank": 41
                    }, 
                    {
                        "name": "service information developer", 
                        "rank": 42
                    }, 
                    {
                        "name": "software technical manager", 
                        "rank": 43
                    }, 
                    {
                        "name": "software tools developer", 
                        "rank": 44
                    }, 
                    {
                        "name": "automation tools developer", 
                        "rank": 45
                    }, 
                    {
                        "name": "software developer freelancer", 
                        "rank": 46
                    }, 
                    {
                        "name": "analyst developer", 
                        "rank": 47
                    }, 
                    {
                        "name": "technical developer", 
                        "rank": 48
                    }, 
                    {
                        "name": "computer software engineer", 
                        "rank": 49
                    }, 
                    {
                        "name": "software integration specialist", 
                        "rank": 50
                    }, 
                    {
                        "name": "java web application developer", 
                        "rank": 51
                    }, 
                    {
                        "name": "consulting software engineer", 
                        "rank": 52
                    }, 
                    {
                        "name": "undergraduate software engineer", 
                        "rank": 53
                    }, 
                    {
                        "name": "specialist software developer", 
                        "rank": 54
                    }, 
                    {
                        "name": "contracted software developer", 
                        "rank": 55
                    }, 
                    {
                        "name": "project manager software developer", 
                        "rank": 56
                    }, 
                    {
                        "name": "enterprise software developer", 
                        "rank": 57
                    }, 
                    {
                        "name": "freelance software engineer", 
                        "rank": 58
                    }, 
                    {
                        "name": "coop software engineer", 
                        "rank": 59
                    }, 
                    {
                        "name": "coop software developer", 
                        "rank": 60
                    }, 
                    {
                        "name": "principle software developer", 
                        "rank": 61
                    }, 
                    {
                        "name": "software engineering team leader", 
                        "rank": 62
                    }, 
                    {
                        "name": "electronic payment systems designer", 
                        "rank": 63
                    }, 
                    {
                        "name": "research software engineer", 
                        "rank": 64
                    }, 
                    {
                        "name": "graduate developer", 
                        "rank": 65
                    }, 
                    {
                        "name": "programmer web developer databasedeveloper", 
                        "rank": 66
                    }, 
                    {
                        "name": "freelancer software engineer", 
                        "rank": 67
                    }, 
                    {
                        "name": "software engineer developer", 
                        "rank": 68
                    }, 
                    {
                        "name": "graduate programmer", 
                        "rank": 69
                    }, 
                    {
