=== seanthorne/TalentIQ-V3-API-Resources/schemas/person-search/person-search-response-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "errors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    }
                }
            }
        },
        "message": {
            "type": "string"
        },
        "status": {
            "type": "number"
        },
        "hits": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "number"
                },
                "max_score": {
                    "type": "number"
                },
                "hits": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "_score": {
                                "type": "number"
                            },
                            "_source": {
                                "type": "schemas/person/person.json"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== seanthorne/TalentIQ-V3-API-Resources/examples/person_search_response_success.json
{
	"status": 200,
	"errors": [],
	"message": "Success",
	"hits": {
		"total": 3291,
		"max_score": 1.0,
		"hits": [
			{
				"_score": 1.0,
				"_source": {
				    "education": [
				        {
				            "is_current": null,
				            "degree": "Bachelor of Science",
				            "end_date": "2014",
				            "start_date": "2010",
				            "locations": [
				                {
				                    "continent": "North America",
				                    "country": "United States",
				                    "geo": "44.06,-123.19",
				                    "locality": "Eugene",
				                    "name": "Eugene, Oregon, United States",
				                    "street_address": null,
				                    "po_box": null,
				                    "postal_code": null,
				                    "type": "locality",
				                    "is_primary": null,
				                    "region": "Oregon"
				                }
				            ],
				            "majors": [
				                "Business Administration"
				            ],
				            "minors": [
				                "Entrepreneurship"
				            ],
				            "school": {
				                "location": "Eugene, Oregon, United States",
				                "name": "University of Oregon",
				                "website": "http://www.uoregon.edu",
				                "profiles": ["http://www.linkedin.com/edu/university-of-oregon-19207"]
				            }
				        }
				    ],
				    "emails": [
				        {
				            "address": "sean@talentiq.co",
				            "is_primary": null,
				            "type": "professional",
				            "domain": "talentiq.co",
				            "local": "sean"
				        },
				        {
				            "address": "sean@hallspot.com",
				            "is_primary": null,
				            "type": "professional",
				            "domain": "hallspot.com",
				            "local": "sean"
				        },
				        {
				            "address": "seanthorne5@gmail.com",
				            "is_primary": null,
				            "type": "personal",
				            "domain": "gmail.com",
				            "local": "seanthorne5"
				        }
				    ],
				    "industries": [
				        {
				            "is_primary": null,
				            "name": "Computer Software"
				        },
				        {
				            "is_primary": null,
				            "name": "Sales & Marketing"
				        }
				    ],
				    "experience": [
				        {
				            "is_current": null,
				            "company": {
				                "industry": "Computer Software",
				                "location": "San Francisco, California, United States",
				                "name": "TalentIQ Technologies",
				                "size": "11-50",
				                "website": "http://www.talentiq.co",
				                "profiles": ["http://www.linkedin.com/company/talentiq"]
				            },
				            "title": {
				                "name": "Co-Founder & CEO",
				                "levels": ["Co-Founder", "CEO", "C", "Executive", "Chief Executive Officer"],
				                "functions": []
				            },
				            "start_date": "2015",
				            "end_date": null,
				            "locations": [
				                {
				                    "continent": "North America",
				                    "country": "United States",
				                    "geo": "37.79,-122.39",
				                    "locality": "San Francisco",
				                    "name": "San Francisco, California, United States",
				                    "street_address": null,
				                    "po_box": null,
				                    "postal_code": null,
				                    "type": "locality",
				                    "is_primary": null,
				                    "region": "California"
				                }
				            ]
				        }
				    ],
				    "interests": [
				        {
				            "name": "Golf"
				        },
				        {
				            "name": "Coffee"
				        },
				        {
				            "name": "History"
				        }
				    ],
				    "locations": [
				        {
				            "continent": "North America",
				            "country": "United States",
				            "geo": "37.79,-122.39",
				            "locality": "San Francisco",
				            "name": "San Francisco, California, United States",
				            "street_address": null,
				            "po_box": null,
				            "postal_code": null,
				            "type": "locality",
				            "is_primary": null,
				            "region": "California"
				        },
				        {
				            "continent": "North America",
				            "country": "United States",
				            "geo": "44.06,-123.19",
				            "locality": "Eugene",
				            "name": "Eugene, Oregon, United States",
				            "street_address": null,
				            "po_box": null,
				            "postal_code": null,
				            "type": "locality",
				            "is_primary": null,
				            "region": "Oregon"
				        },
				        {
				            "continent": "North America",
				            "country": "United States",
				            "geo": "45.54,-122.79",
				            "locality": "Portland",
				            "name": "Portland, Oregon, United States",
				            "street_address": null,
				            "po_box": null,
				            "postal_code": null,
				            "type": "locality",
				            "is_primary": null,
				            "region": "Oregon"
				        }
				    ],
				    "names": [
				        {
				            "clean": "sean thorne",
				            "name": "Sean F Thorne",
				            "last_name": "Thorne",
				            "first_name": "Sean",
				            "pedigree": null,
				            "suffix": null,
				            "title": "Mr.",
				            "name": "Sean F Thorne",
				            "middle_name": null,
				            "is_primary": true,
				            "first_initial": "s",
				            "last_initial": "t",
				            "middle_initial": "f"
				        }
				    ],
				    "phone_numbers": [
				        {
				            "E164": "+14155688415",
				            "area_code": "415",
				            "country_code": "1",
				            "number": "+1 (415) 568-8415",
				            "national_number": "4155688415",
				            "type": "personal",
				            "extension": "null"
				        }
				    ],
				    "photos": [
				        {
				            "source": null,
				            "url": "https://d1qb2nb5cznatu.cloudfront.net/users/276254-large?1458341112"
				        }
				    ],
				    "profiles": [
				        {
				            "aliases": [],
				            "ids": [],
				            "clean": "linkedin.com/in/seanthorne",
				            "network": "linkedin",
				            "url": "http://www.linkedin.com/in/seanthorne",
				            "username": "in/seanthorne"
				        }
				    ],
				    "skills": [
				        {
				            "name": "Entrepreneurship"
				        },
				        {
				            "name": "Sales"
				        },
				        {
				            "name": "Marketing"
				        }
				    ],
				    "websites": [
				        {
				            "is_primary": null,
				            "type": "personal",
				            "url": "http://www.seanthorne.com",
				            "domain": "seanthorne.com"
				        }
				    ]
				}
			}
		]
	}
}
