=== seanthorne/TalentIQ-V3-API-Resources/schemas/company/company-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
   "properties": {
        "date_closed": {
            "type": ["null", "string"]
        }, 
        "date_founded": {
            "type": ["null", "string"]
        }, 
        "emails": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "address": {
	                    "type": "string"
	                }, 
	                "is_primary": {
	                    "type": ["null", "boolean"]
	                }, 
	                "is_valid": {
	                    "type": ["null", "boolean"]
	                }, 
	                "type": {
	                    "type": ["string", "null"]
	                },
	                "domain": {
	                    "type": ["string", "null"]
	                },
	                "local": {
	                    "type": ["string", "null"]
	                }
	            }
            }
        }, 
        "industries": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "is_primary": {
	                    "type": ["null", "boolean"]
	                }, 
	                "name": {
	                    "type": "string"
	                }
	            }
            }
        }, 
        "is_active": {
            "type": ["null", "boolean"]
        }, 
        "locations": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "continent": {
	                    "type": ["string", "null"]
	                }, 
	                "country": {
	                    "type": ["string", "null"]
	                }, 
	                "geo": {
	                    "type": ["string", "null"]
	                }, 
	                "type": {
	                    "type": ["string", "null"]
	                }, 
	                "is_primary": {
	                    "type": ["null", "boolean"]
	                }, 
	                "locality": {
	                    "type": ["string", "null"]
	                }, 
	                "name": {
	                    "type": ["string", "null"]
	                }, 
	                "po_box": {
	                    "type": ["string", "null"]
	                }, 
	                "postal_code": {
	                    "type": ["string", "null"]
	                }, 
	                "region": {
	                    "type": ["string", "null"]
	                }, 
	                "street_address": {
	                    "type": ["string", "null"]
	                }
	            }
            }
        }, 
        "names": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "clean": {
	                    "type": ["string", "null"]
	                }, 
	                "is_primary": {
	                    "type": ["null", "boolean"]
	                }, 
	                "name": {
	                    "type": "string"
	                }
	            }
            }
        }, 
        "phone_numbers": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "E164": {
	                    "type": ["string", "null"]
	                }, 
	                "area_code": {
	                    "type": ["string", "null"]
	                },
	                "country_code": {
	                    "type": ["string", "null"]
	                }, 
	                "extension": {
	                    "type": ["string", "null"]
	                }, 
	                "is_primary": {
	                    "type": ["null", "boolean"]
	                }, 
	                "is_valid": {
	                    "type": ["null", "boolean"]
	                }, 
	                "national_number": {
	                    "type": ["string", "null"]
	                }, 
	                "number": {
	                    "type": "string"
	                }, 
	                "type": {
	                    "type": ["string", "null"]
	                }
	            }
            }
        }, 
        "profiles": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "aliases": {
	                	"type": "array",
	                	"items": {
	                		"type": "string"
	                	}
	                }, 
	                "ids": {
	                	"type": "array",
	                	"items": {
	                		"type": "string"
	                	}
	                }, 
	                "clean": {
	                	"type": ["null", "string"]
                	},
	                "network": {
	                    "type": ["string", "null"]
	                }, 
	                "url": {
	                    "type": ["string", "null"]
	                }, 
	                "username": {
	                    "type": ["string", "null"]
	                }
	            }
        	}
        }, 
        "size": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "date": {
	                    "type": ["null", "string"]
	                }, 
	                "text": {
	                	"type": ["null", "string"]
	                },
	                "range": {
	                	"type": "object",
	                    "properties": {
	                        "high": {
	                            "type": ["null", "integer"]
	                        }, 
	                        "low": {
	                            "type": ["null", "integer"]
	                        }
	                    }
	                }
	            }
            }
        }, 
        "tags": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "name": {
	                    "type": "string"
	                }
	            }
            }
        }, 
        "summaries": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "text": {
	                    "type": "string"
	                }
	            }
            }
        }, 
        "websites": {
        	"type": "array",
        	"items": {
        		"type": "object",
	            "properties": {
	                "domain": {
	                    "type": ["string", "null"]
	                }, 
	                "type": {
	                    "type": ["string", "null"]
	                }, 
	                "is_primary": {
	                    "type": ["null", "boolean"]
	                }, 
	                "url": {
	                    "type": "string"
	                }
	            }
            }
        }
    }
}

=== seanthorne/TalentIQ-V3-API-Resources/schemas/company/company-example.json
{
    "date_closed": null, 
    "date_founded": "2015", 
    "emails": [
        {
            "address": "sales@talentiq.co", 
            "domain": "talentiq.co", 
            "is_primary": true, 
            "is_valid": true, 
            "local": "sales", 
            "type": "professional"
        }, 
        {
            "address": "support@talentiq.co", 
            "domain": "talentiq.co", 
            "is_primary": true, 
            "is_valid": true, 
            "local": "support", 
            "type": "professional"
        }
    ], 
    "industries": [
        {
            "is_primary": true, 
            "name": "computer software"
        }
    ], 
    "is_active": true, 
    "locations": [
        {
            "continent": "north america", 
            "country": "united states", 
            "geo": "37.79,-122.39", 
            "is_primary": true, 
            "locality": "san francisco", 
            "name": "san francisco, california, united states", 
            "po_box": null, 
            "postal_code": null, 
            "region": "california", 
            "street_address": null, 
            "type": "locality"
        }, 
        {
            "continent": "north america", 
            "country": "united states", 
            "geo": "45.5236111,-122.675", 
            "is_primary": null, 
            "locality": "portland", 
            "name": "portland, oregon, united states", 
            "po_box": "1", 
            "postal_code": "97204", 
            "region": "oregon", 
            "street_address": "519 sw 3rd ave", 
            "type": "locality"
        }
    ], 
    "names": [
        {
            "clean": "talentiqtechnologies", 
            "is_primary": true, 
            "name": "talentiq technologies"
        }, 
        {
            "clean": "talentiq", 
            "is_primary": false, 
            "name": "talentiq inc."
        }, 
        {
            "clean": "talentiq", 
            "is_primary": false, 
            "name": "talentiq"
        }
    ], 
    "phone_numbers": [
        {
            "E164": "+19716784935", 
            "area_code": "971", 
            "country_code": "1", 
            "extension": "1", 
            "is_active": null, 
            "is_valid": true, 
            "national_number": "9716784935", 
            "number": "(971) 678-4935 ext. 1"
        }
    ], 
    "profiles": [
        {
            "aliases": [
                "http://www.linkedin.com/company/6404208"
            ], 
            "clean": "linkedin.com/company/talentiq", 
            "ids": [
                "6404208"
            ], 
            "network": "linkedin", 
            "url": "http://www.linkedin.com/company/talentiq", 
            "username": "company/talentiq"
        }
    ], 
    "size": [
        {
            "date": "2016", 
            "range": {
                "high": 50, 
                "low": 11
            }, 
            "text": "11-50"
        }
    ], 
    "summaries": [
        {
            "text": "talentiq's enrichment, normalization, and deduplication apis enable enterprises to make better use of the data they already have."
        }
    ], 
    "tags": [
        {
            "name": "human resources"
        },
        {
            "name": "data"
        },
        {
            "name": "data analytics"
        },
        {
            "name": "people intelligence"
        }
    ], 
    "websites": [
        {
            "domain": "talentiq.co", 
            "is_primary": true, 
            "url": "http://www.talentiq.co",
            "type": null
        }
    ]
}
