=== seanthorne/TalentIQ-V3-API-Resources/schemas/person/person-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "education": {
            "items": {
                "properties": {
                    "is_current": ["boolean", "null"],
                    "degree": {
                        "type": ["string", "null"]
                    },
                    "end_date": {
                        "type": ["string", "null"]
                    },
                    "locations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "continent": {
                                    "type": ["string", "null"]
                                },
                                "country": {
                                    "type": ["string", "null"]
                                },
                                "geo": {
                                    "type": ["string", "null"]
                                },
                                "type": {
                                    "type": ["string", "null"]
                                },
                                "is_primary": {
                                    "type": ["null", "boolean"]
                                },
                                "locality": {
                                    "type": ["string", "null"]
                                },
                                "name": {
                                    "type": ["string", "null"]
                                },
                                "po_box": {
                                    "type": ["string", "null"]
                                },
                                "postal_code": {
                                    "type": ["string", "null"]
                                },
                                "region": {
                                    "type": ["string", "null"]
                                },
                                "street_address": {
                                    "type": ["string", "null"]
                                }
                            }
                        }
                    },
                    "majors": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "degrees": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "minors": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "school": {
                        "type": "object",
                        "properties": {
                            "location": {
                                "type": ["string", "null"]
                            },
                            "name": {
                                "type": ["string", "null"]
                            },
                            "website": {
                                "type": ["string", "null"]
                            },
                            "profiles": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "start_date": {
                        "type": ["string", "null"]
                    }
                }
            },
            "type": "array"
        },
        "emails": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "type": {
                        "type": ["string", "null"]
                    },
                    "domain": {
                        "type": ["string", "null"]
                    },
                    "local": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "industries": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "name": {
                        "type": "string"
                    }
                }
            }
        },
        "experience": {
            "items": {
                "properties": {
                    "is_current": ["boolean", "null"],
                    "company": {
                        "type": "object",
                        "properties": {
                            "industry": {
                                "type": ["string", "null"]
                            },
                            "location": {
                                "type": ["string", "null"]
                            },
                            "name": {
                                "type": ["string", "null"]
                            },
                            "size": {
                                "type": ["string", "null"]
                            },
                            "website": {
                                "type": ["string", "null"]
                            },
                            "profiles": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "end_date": {
                        "type": ["string", "null"]
                    },
                    "locations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "continent": {
                                    "type": ["string", "null"]
                                },
                                "country": {
                                    "type": ["string", "null"]
                                },
                                "geo": {
                                    "type": ["string", "null"]
                                },
                                "type": {
                                    "type": ["string", "null"]
                                },
                                "is_primary": {
                                    "type": ["null", "boolean"]
                                },
                                "locality": {
                                    "type": ["string", "null"]
                                },
                                "name": {
                                    "type": ["string", "null"]
                                },
                                "po_box": {
                                    "type": ["string", "null"]
                                },
                                "postal_code": {
                                    "type": ["string", "null"]
                                },
                                "region": {
                                    "type": ["string", "null"]
                                },
                                "street_address": {
                                    "type": ["string", "null"]
                                }
                            }
                        }
                    },
                    "start_date": {
                        "type": ["string", "null"]
                    },
                    "title": {
                        "type": "object",
                        "properties": {
                            "functions": {
                                "type": "array",
                                "items": {
                                    "type": ["string", "null"]
                                }
                            },
                            "levels": {
                                "type": "array",
                                "items": {
                                    "type": ["string", "null"]
                                }
                            },
                            "name": {
                                "type": ["string", "null"]
                            }
                        }
                    }
                }
            },
            "type": "array"
        },
        "interests": {
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        },
        "locations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "continent": {
                        "type": ["string", "null"]
                    },
                    "country": {
                        "type": ["string", "null"]
                    },
                    "geo": {
                        "type": ["string", "null"]
                    },
                    "type": {
                        "type": ["string", "null"]
                    },
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "locality": {
                        "type": ["string", "null"]
                    },
                    "name": {
                        "type": ["string", "null"]
                    },
                    "po_box": {
                        "type": ["string", "null"]
                    },
                    "postal_code": {
                        "type": ["string", "null"]
                    },
                    "region": {
                        "type": ["string", "null"]
                    },
                    "street_address": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "names": {
            "items": {
                "type": "object",
                "properties": {
                    "clean": {
                        "type": ["string", "null"]
                    },
                    "first_name": {
                        "type": ["string", "null"]
                    },
                    "is_primary": {
                        "type": ["boolean", "null"]
                    },
                    "last_name": {
                        "type": ["string", "null"]
                    },
                    "middle_name": {
                        "type": ["string", "null"]
                    },
                    "name": {
                        "type": ["string", "null"]
                    },
                    "pedigree": {
                        "type": ["string", "null"]
                    },
                    "suffix": {
                        "type": ["string", "null"]
                    },
                    "title": {
                        "type": ["string", "null"]
                    }
                }
            },
            "type": "array"
        },
        "phone_numbers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "E164": {
                        "type": ["string", "null"]
                    },
                    "area_code": {
                        "type": ["string", "null"]
                    },
                    "country_code": {
                        "type": ["string", "null"]
                    },
                    "extension": {
                        "type": ["string", "null"]
                    },
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "national_number": {
                        "type": ["string", "null"]
                    },
                    "number": {
                        "type": "string"
                    },
                    "type": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "photos": {
            "items": {
                "type": "object",
                "properties": {
                    "source": {
                        "type": ["string", "null"]
                    },
                    "url": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        },
        "profiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "aliases": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "ids": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "clean": {
                        "type": ["string", "null"]
                    },
                    "is_active": {
                        "type": ["null", "boolean"]
                    },
                    "network": {
                        "type": ["string", "null"]
                    },
                    "url": {
                        "type": ["string", "null"]
                    },
                    "username": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "skills": {
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        },
        "websites": {
            "items": {
                "type": "object",
                "properties": {
                    "is_primary": {
                        "type": ["boolean", "null"]
                    },
                    "type": {
                        "type": ["string", "null"]
                    },
                    "url": {
                        "type": "string"
                    },
                    "domain": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        }
    }
}

=== seanthorne/TalentIQ-V3-API-Resources/schemas/person/person-example.json
{
    "education": [
        {
            "degree": "bachelor of science", 
            "end_date": "2014", 
            "is_current": null, 
            "locations": [
                {
                    "continent": "north america", 
                    "country": "united states", 
                    "geo": "44.06,-123.19", 
                    "is_primary": null, 
                    "locality": "eugene", 
                    "name": "eugene, oregon, united states", 
                    "po_box": null, 
                    "postal_code": null, 
                    "region": "oregon", 
                    "street_address": null, 
                    "type": "locality"
                }
            ], 
            "majors": [
                "business administration"
            ], 
            "minors": [
                "entrepreneurship"
            ], 
            "school": {
                "location": "eugene, oregon, united states", 
                "name": "university of oregon", 
                "profiles": [
                    "linkedin.com/edu/university-of-oregon-19207"
                ], 
                "website": "http://www.uoregon.edu"
            }, 
            "start_date": "2010"
        }
    ], 
    "emails": [
        {
            "address": "sean@talentiq.co", 
            "domain": "talentiq.co", 
            "is_primary": null, 
            "local": "sean", 
            "type": "professional"
        }, 
        {
            "address": "sean@hallspot.com", 
            "domain": "hallspot.com", 
            "is_primary": null, 
            "local": "sean", 
            "type": "professional"
        }, 
        {
            "address": "seanthorne5@gmail.com", 
            "domain": "gmail.com", 
            "is_primary": null, 
            "local": "seanthorne5", 
            "type": "personal"
        }
    ], 
    "experience": [
        {
            "company": {
                "industry": "computer software", 
                "location": "san francisco, california, united states", 
                "name": "talentiq technologies", 
                "profiles": [
                    "linkedin.com/company/talentiq"
                ], 
                "size": "11-50", 
                "website": "http://www.talentiq.co"
            }, 
            "end_date": null, 
            "is_current": null, 
            "locations": [
                {
                    "continent": "north america", 
                    "country": "united states", 
                    "geo": "37.79,-122.39", 
                    "is_primary": null, 
                    "locality": "san francisco", 
                    "name": "san francisco, california, united states", 
                    "po_box": null, 
                    "postal_code": null, 
                    "region": "california", 
                    "street_address": null, 
                    "type": "locality"
                }
            ], 
            "start_date": "2015", 
            "title": {
                "functions": [], 
                "levels": [
                    "co-founder", 
                    "ceo", 
                    "c", 
                    "executive", 
                    "chief executive officer"
                ], 
                "name": "co-founder & ceo"
            }
        },
        {
            "company": {
                "industry": "computer software", 
                "location": null, 
                "name": "hallspot", 
                "profiles": [
                    "linkedin.com/company/hallspot", 
                    "linkedin.com/company/3019184"
                ], 
                "size": null, 
                "website": "http://www.hallspot.com"
            }, 
            "end_date": "2015", 
            "is_current": null, 
            "locations": [], 
            "start_date": "2012", 
            "title": {
                "functions": [], 
                "levels": [
                    "founder", 
                    "co-founder"
                ], 
                "name": "co-founder"
            }
        },
        {
            "company": {
                "industry": "internet", 
                "location": null, 
                "name": "datemyschool", 
                "profiles": [
                    "linkedin.com/company/datemyschool", 
                    "linkedin.com/company/1977175"
                ], 
                "size": null, 
                "website": "http://www.datemyschool.com"
            }, 
            "end_date": "2012", 
            "is_current": null, 
            "locations": [], 
            "start_date": "2012", 
            "title": {
                "functions": [
                    "manager", 
                    "marketing manager"
                ], 
                "levels": [
                ], 
                "name": "marketing manager"
            }
        }
    ], 
    "industries": [
        {
            "is_primary": null, 
            "name": "computer software"
        }, 
        {
            "is_primary": null, 
            "name": "sales & marketing"
        }
    ], 
    "interests": [
        {
            "name": "golf"
        }, 
        {
            "name": "coffee"
        }, 
        {
            "name": "history"
        }
    ], 
    "locations": [
        {
            "continent": "north america", 
            "country": "united states", 
            "geo": "37.79,-122.39", 
            "is_primary": null, 
            "locality": "san francisco", 
            "name": "san francisco, california, united states", 
            "po_box": null, 
            "postal_code": null, 
            "region": "california", 
            "street_address": null, 
            "type": "locality"
        }, 
        {
            "continent": "north america", 
            "country": "united states", 
            "geo": "37.89,-122.33", 
            "is_primary": null, 
            "locality": "albany", 
            "name": "albany, california, united states", 
            "po_box": null, 
            "postal_code": "94706", 
            "region": "california", 
            "street_address": "730 pomona ave", 
            "type": "locality"
        }, 
        {
            "continent": "north america", 
            "country": "united states", 
            "geo": "44.06,-123.19", 
            "is_primary": null, 
            "locality": "eugene", 
            "name": "eugene, oregon, united states", 
            "po_box": null, 
            "postal_code": null, 
            "region": "oregon", 
            "street_address": null, 
            "type": "locality"
        }, 
        {
            "continent": "north america", 
            "country": "united states", 
            "geo": "45.54,-122.79", 
            "is_primary": null, 
            "locality": "portland", 
            "name": "portland, oregon, united states", 
            "po_box": null, 
            "postal_code": null, 
            "region": "oregon", 
            "street_address": null, 
            "type": "locality"
        }
    ], 
    "names": [
        {
            "clean": "sean thorne", 
            "first_name": "sean", 
            "is_primary": true, 
            "last_name": "thorne", 
            "middle_name": null, 
            "name": "sean f thorne", 
            "pedigree": null, 
            "suffix": null, 
            "title": "mr."
        }
    ], 
    "phone_numbers": [
        {
            "E164": "+14155688415", 
            "area_code": "415", 
            "country_code": "1", 
            "extension": "null", 
            "national_number": "4155688415", 
            "number": "+1 (415) 568-8415", 
            "type": "personal"
        }
    ], 
    "photos": [
        {
            "source": null, 
            "url": "https://d1qb2nb5cznatu.cloudfront.net/users/276254-large?1458341112"
        }
    ], 
    "profiles": [
        {
            "aliases": [], 
            "clean": "linkedin.com/in/seanthorne", 
            "ids": [], 
            "network": "linkedin", 
            "url": "http://www.linkedin.com/in/seanthorne", 
            "username": "in/seanthorne"
        }
    ], 
    "skills": [
        {
            "name": "entrepreneurship"
        }, 
        {
            "name": "sales"
        }, 
        {
            "name": "marketing"
        }
    ], 
    "websites": [
        {
            "domain": "seanthorne.com", 
            "is_primary": null, 
            "type": "personal", 
            "url": "http://www.seanthorne.com"
        }
    ]
}
