=== seanthorne/TalentIQ-V3-API-Resources/schemas/person/person-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "education": {
            "items": {
                "properties": {
                    "is_current": ["boolean", "null"],
                    "degree": {
                        "type": ["string", "null"]
                    },
                    "end_date": {
                        "type": ["string", "null"]
                    },
                    "locations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "continent": {
                                    "type": ["string", "null"]
                                },
                                "country": {
                                    "type": ["string", "null"]
                                },
                                "geo": {
                                    "type": ["string", "null"]
                                },
                                "type": {
                                    "type": ["string", "null"]
                                },
                                "is_primary": {
                                    "type": ["null", "boolean"]
                                },
                                "locality": {
                                    "type": ["string", "null"]
                                },
                                "name": {
                                    "type": ["string", "null"]
                                },
                                "po_box": {
                                    "type": ["string", "null"]
                                },
                                "postal_code": {
                                    "type": ["string", "null"]
                                },
                                "region": {
                                    "type": ["string", "null"]
                                },
                                "street_address": {
                                    "type": ["string", "null"]
                                }
                            }
                        }
                    },
                    "majors": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "degrees": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "minors": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "school": {
                        "type": "object",
                        "properties": {
                            "location": {
                                "type": ["string", "null"]
                            },
                            "name": {
                                "type": ["string", "null"]
                            },
                            "website": {
                                "type": ["string", "null"]
                            },
                            "profiles": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "start_date": {
                        "type": ["string", "null"]
                    }
                }
            },
            "type": "array"
        },
        "emails": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "type": {
                        "type": ["string", "null"]
                    },
                    "domain": {
                        "type": ["string", "null"]
                    },
                    "local": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "industries": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "name": {
                        "type": "string"
                    }
                }
            }
        },
        "experience": {
            "items": {
                "properties": {
                    "is_current": ["boolean", "null"],
                    "company": {
                        "type": "object",
                        "properties": {
                            "industry": {
                                "type": ["string", "null"]
                            },
                            "location": {
                                "type": ["string", "null"]
                            },
                            "name": {
                                "type": ["string", "null"]
                            },
                            "size": {
                                "type": ["string", "null"]
                            },
                            "website": {
                                "type": ["string", "null"]
                            },
                            "profiles": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "end_date": {
                        "type": ["string", "null"]
                    },
                    "locations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "continent": {
                                    "type": ["string", "null"]
                                },
                                "country": {
                                    "type": ["string", "null"]
                                },
                                "geo": {
                                    "type": ["string", "null"]
                                },
                                "type": {
                                    "type": ["string", "null"]
                                },
                                "is_primary": {
                                    "type": ["null", "boolean"]
                                },
                                "locality": {
                                    "type": ["string", "null"]
                                },
                                "name": {
                                    "type": ["string", "null"]
                                },
                                "po_box": {
                                    "type": ["string", "null"]
                                },
                                "postal_code": {
                                    "type": ["string", "null"]
                                },
                                "region": {
                                    "type": ["string", "null"]
                                },
                                "street_address": {
                                    "type": ["string", "null"]
                                }
                            }
                        }
                    },
                    "start_date": {
                        "type": ["string", "null"]
                    },
                    "title": {
                        "type": "object",
                        "properties": {
                            "functions": {
                                "type": "array",
                                "items": {
                                    "type": ["string", "null"]
                                }
                            },
                            "levels": {
                                "type": "array",
                                "items": {
                                    "type": ["string", "null"]
                                }
                            },
                            "name": {
                                "type": ["string", "null"]
                            }
                        }
                    }
                }
            },
            "type": "array"
        },
        "interests": {
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        },
        "locations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "continent": {
                        "type": ["string", "null"]
                    },
                    "country": {
                        "type": ["string", "null"]
                    },
                    "geo": {
                        "type": ["string", "null"]
                    },
                    "type": {
                        "type": ["string", "null"]
                    },
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "locality": {
                        "type": ["string", "null"]
                    },
                    "name": {
                        "type": ["string", "null"]
                    },
                    "po_box": {
                        "type": ["string", "null"]
                    },
                    "postal_code": {
                        "type": ["string", "null"]
                    },
                    "region": {
                        "type": ["string", "null"]
                    },
                    "street_address": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "names": {
            "items": {
                "type": "object",
                "properties": {
                    "clean": {
                        "type": ["string", "null"]
                    },
                    "first_name": {
                        "type": ["string", "null"]
                    },
                    "is_primary": {
                        "type": ["boolean", "null"]
                    },
                    "last_name": {
                        "type": ["string", "null"]
                    },
                    "middle_name": {
                        "type": ["string", "null"]
                    },
                    "name": {
                        "type": ["string", "null"]
                    },
                    "pedigree": {
                        "type": ["string", "null"]
                    },
                    "suffix": {
                        "type": ["string", "null"]
                    },
                    "title": {
                        "type": ["string", "null"]
                    }
                }
            },
            "type": "array"
        },
        "phone_numbers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "E164": {
                        "type": ["string", "null"]
                    },
                    "area_code": {
                        "type": ["string", "null"]
                    },
                    "country_code": {
                        "type": ["string", "null"]
                    },
                    "extension": {
                        "type": ["string", "null"]
                    },
                    "is_primary": {
                        "type": ["null", "boolean"]
                    },
                    "national_number": {
                        "type": ["string", "null"]
                    },
                    "number": {
                        "type": "string"
                    },
                    "type": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "photos": {
            "items": {
                "type": "object",
                "properties": {
                    "source": {
                        "type": ["string", "null"]
                    },
                    "url": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        },
        "profiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "aliases": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "ids": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "clean": {
                        "type": ["string", "null"]
                    },
                    "is_active": {
                        "type": ["null", "boolean"]
                    },
                    "network": {
                        "type": ["string", "null"]
                    },
                    "url": {
                        "type": ["string", "null"]
                    },
                    "username": {
                        "type": ["string", "null"]
                    }
                }
            }
        },
        "skills": {
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        },
        "websites": {
            "items": {
                "type": "object",
                "properties": {
                    "is_primary": {
                        "type": ["boolean", "null"]
                    },
                    "type": {
                        "type": ["string", "null"]
                    },
                    "url": {
                        "type": "string"
                    },
                    "domain": {
                        "type": "string"
                    }
                }
            },
            "type": "array"
        }
    }
}

=== seanthorne/TalentIQ-V3-API-Resources/examples/person.json
{
    "education": [
        {
            "is_current": null,
            "degree": "Bachelor of Science",
            "end_date": "2014",
            "start_date": "2010",
            "locations": [
                {
                    "continent": "North America",
                    "country": "United States",
                    "geo": "44.06,-123.19",
                    "locality": "Eugene",
                    "name": "Eugene, Oregon, United States",
                    "street_address": null,
                    "po_box": null,
                    "postal_code": null,
                    "type": "locality",
                    "is_primary": null,
                    "region": "Oregon"
                }
            ],
            "majors": [
                "Business Administration"
            ],
            "minors": [
                "Entrepreneurship"
            ],
            "school": {
                "location": "Eugene, Oregon, United States",
                "name": "University of Oregon",
                "website": "http://www.uoregon.edu",
                "profiles": ["http://www.linkedin.com/edu/university-of-oregon-19207"]
            }
        }
    ],
    "emails": [
        {
            "address": "sean@talentiq.co",
            "is_primary": null,
            "type": "professional",
            "domain": "talentiq.co",
            "local": "sean"
        },
        {
            "address": "sean@hallspot.com",
            "is_primary": null,
            "type": "professional",
            "domain": "hallspot.com",
            "local": "sean"
        },
        {
            "address": "seanthorne5@gmail.com",
            "is_primary": null,
            "type": "personal",
            "domain": "gmail.com",
            "local": "seanthorne5"
        }
    ],
    "industries": [
        {
            "is_primary": null,
            "name": "Computer Software"
        },
        {
            "is_primary": null,
            "name": "Sales & Marketing"
        }
    ],
    "experience": [
        {
            "is_current": null,
            "company": {
                "industry": "Computer Software",
                "location": "San Francisco, California, United States",
                "name": "TalentIQ Technologies",
                "size": "11-50",
                "website": "http://www.talentiq.co",
                "profiles": ["http://www.linkedin.com/company/talentiq"]
            },
            "title": {
                "name": "Co-Founder & CEO",
                "levels": ["Co-Founder", "CEO", "C", "Executive", "Chief Executive Officer"],
                "functions": []
            },
            "start_date": "2015",
            "end_date": null,
            "locations": [
                {
                    "continent": "North America",
                    "country": "United States",
                    "geo": "37.79,-122.39",
                    "locality": "San Francisco",
                    "name": "San Francisco, California, United States",
                    "street_address": null,
                    "po_box": null,
                    "postal_code": null,
                    "type": "locality",
                    "is_primary": null,
                    "region": "California"
                }
            ]
        }
    ],
    "interests": [
        {
            "name": "Golf"
        },
        {
            "name": "Coffee"
        },
        {
            "name": "History"
        }
    ],
    "locations": [
        {
            "continent": "North America",
            "country": "United States",
            "geo": "37.79,-122.39",
            "locality": "San Francisco",
            "name": "San Francisco, California, United States",
            "street_address": null,
            "po_box": null,
            "postal_code": null,
            "type": "locality",
            "is_primary": null,
            "region": "California"
        },
        {
            "continent": "North America",
            "country": "United States",
            "geo": "44.06,-123.19",
            "locality": "Eugene",
            "name": "Eugene, Oregon, United States",
            "street_address": null,
            "po_box": null,
            "postal_code": null,
            "type": "locality",
            "is_primary": null,
            "region": "Oregon"
        },
        {
            "continent": "North America",
            "country": "United States",
            "geo": "45.54,-122.79",
            "locality": "Portland",
            "name": "Portland, Oregon, United States",
            "street_address": null,
            "po_box": null,
            "postal_code": null,
            "type": "locality",
            "is_primary": null,
            "region": "Oregon"
        }
    ],
    "names": [
        {
            "clean": "sean thorne",
            "name": "Sean F Thorne",
            "last_name": "Thorne",
            "first_name": "Sean",
            "pedigree": null,
            "suffix": null,
            "title": "Mr.",
            "name": "Sean F Thorne",
            "middle_name": null,
            "is_primary": true,
            "first_initial": "s",
            "last_initial": "t",
            "middle_initial": "f"
        }
    ],
    "phone_numbers": [
        {
            "E164": "+14155688415",
            "area_code": "415",
            "country_code": "1",
            "number": "+1 (415) 568-8415",
            "national_number": "4155688415",
            "type": "personal",
            "extension": "null"
        }
    ],
    "photos": [
        {
            "source": null,
            "url": "https://d1qb2nb5cznatu.cloudfront.net/users/276254-large?1458341112"
        }
    ],
    "profiles": [
        {
            "aliases": [],
            "ids": [],
            "clean": "linkedin.com/in/seanthorne",
            "network": "linkedin",
            "url": "http://www.linkedin.com/in/seanthorne",
            "username": "in/seanthorne"
        }
    ],
    "skills": [
        {
            "name": "Entrepreneurship"
        },
        {
            "name": "Sales"
        },
        {
            "name": "Marketing"
        }
    ],
    "websites": [
        {
            "is_primary": null,
            "type": "personal",
            "url": "http://www.seanthorne.com",
            "domain": "seanthorne.com"
        }
    ]
}
